import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import record from '../data/train.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(record);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          {
            record.map( (rec, index) => {
              return(
                <>
                  
                  <>{rec.Class == "Eco Plus" ? <div key={index}>
                                                <div>{rec.id}</div>
                                                <div>{rec.Gender}</div>
                                                <div>{rec.Class}</div></div> : <></>}</>
                </>
              )
            })
          }
      </main>
    </>
  )
}
